vault_path: "G:\\Mi unidad\\Obsidian"
project_root: "0_SourceMaterial\\El pizzas\\1_current\\Pizza Stream"
videos_input_dir: "C:\\Users\\franv\\Videos"
ffmpeg_path: "C:\\Users\\franv\\AppData\\Local\\Microsoft\\WinGet\\Packages\\Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe\\ffmpeg-8.0.1-full_build\\bin\\ffmpeg.EXE"
